FROM node:slim

RUN mkdir -p /var/www/app

WORKDIR /var/www/app

ARG NODE_ENV=production
ARG NPM_CONFIG_PRODUCTION=true
ENV NODE_ENV ${NODE_ENV}
ENV NPM_CONFIG_PRODUCTION ${NPM_CONFIG_PRODUCTION}

ADD package.json /var/www/app
RUN npm install
ADD . /var/www/app
RUN npm run build
RUN ls /var/www/app/dist

CMD [ "npm", "start" ]
