FROM node:slim

RUN mkdir -p /var/www/app

WORKDIR /var/www/app

ARG NODE_ENV=development
ARG NPM_CONFIG_PRODUCTION=false
ARG PORT=80

ENV NODE_ENV ${NODE_ENV}
ENV NPM_CONFIG_PRODUCTION ${NPM_CONFIG_PRODUCTION}
ENV PORT ${PORT}

# no pre build in dev mode
#ADD package.json /var/www/app
#RUN npm install
#ADD . /var/www/app
#RUN npm run build

EXPOSE ${PORT}

CMD [ "npm", "start" ]

