version: "2"

services:

### Applications Code Container #############################

    applications:
      volumes:
        - ${APPLICATION}:/var/www
        - ${SSH_AUTH_SOCK}:/ssh-agent

    workspace:
      environment:
        - SSH_AUTH_SOCK=/ssh-agent
